CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    description Text,
    date        DATE,
    label       VARCHAR(100),
    agenda_id   BIGINT       REFERENCES agenda (id) ON DELETE SET NULL

);