CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title       VARCHAR NOT NULL,
    description Text,
    location    VARCHAR,
    start_date   TIMESTAMP,
    end_date     TIMESTAMP,
    agenda_id   BIGINT  REFERENCES agenda (id) ON DELETE SET NULL

);