CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name  VARCHAR,
    first_name VARCHAR,
    email      VARCHAR,
    role       VARCHAR,
    password   VARCHAR,
    agenda_id  BIGINT REFERENCES agenda (id) ON DELETE SET NULL
);